/**
 * Beepo Core MicroserviceLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  CheckAPIServerStatus,
  checkAPIServerStatusSchema,
} from '../models/checkAPIServerStatus';
import { BaseController } from './baseController';

export class ServerStatusController extends BaseController {
  /**
   * **Check the status of the API server by sending a PING request.**
   *
   * @return Response from the API call
   */
  async checkAPIServerStatus(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CheckAPIServerStatus>> {
    const req = this.createRequest('GET', '/server/ping');
    return req.callAsJson(checkAPIServerStatusSchema, requestOptions);
  }
}
