/**
 * Beepo Core MicroserviceLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface AESsymmetricEncryptionRequest {
  message: string;
  key: string;
}

export const aESsymmetricEncryptionRequestSchema: Schema<AESsymmetricEncryptionRequest> = object(
  { message: ['message', string()], key: ['key', string()] }
);
