/**
 * Beepo Core MicroserviceLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, object, Schema, string } from '../schema';

export interface CheckAPIServerStatus {
  beepo: string;
  now: string;
  environment: string;
  timestamp: bigint;
  info: string;
}

export const checkAPIServerStatusSchema: Schema<CheckAPIServerStatus> = object({
  beepo: ['beepo', string()],
  now: ['now', string()],
  environment: ['environment', string()],
  timestamp: ['timestamp', bigint()],
  info: ['info', string()],
});
