/**
 * Beepo Core MicroserviceLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface CreateContextRequest {
  publicKey: string;
}

export const createContextRequestSchema: Schema<CreateContextRequest> = object({
  publicKey: ['publicKey', string()],
});
