/**
 * Beepo Core MicroserviceLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface CreateUSERRequest {
  displayName: string;
  profilePictureUrl: string;
}

export const createUSERRequestSchema: Schema<CreateUSERRequest> = object({
  displayName: ['displayName', string()],
  profilePictureUrl: ['profilePictureUrl', string()],
});
