/**
 * Beepo Core MicroserviceLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Example11 {
  accessToken: string;
  tokenType: string;
}

export const example11Schema: Schema<Example11> = object({
  accessToken: ['accessToken', string()],
  tokenType: ['tokenType', string()],
});
