/**
 * Beepo Core MicroserviceLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Example19 {
  hash: string;
}

export const example19Schema: Schema<Example19> = object({
  hash: ['hash', string()],
});
