/**
 * Beepo Core MicroserviceLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, Schema, string } from '../schema';

export interface Example1 {
  username: string;
  displayName: string;
  profilePictureUrl: string;
  disabled: boolean;
  sourceIpAddress: string;
  id: string;
  uid: string;
  v: number;
}

export const example1Schema: Schema<Example1> = object({
  username: ['username', string()],
  displayName: ['displayName', string()],
  profilePictureUrl: ['profilePictureUrl', string()],
  disabled: ['disabled', boolean()],
  sourceIpAddress: ['sourceIpAddress', string()],
  id: ['_id', string()],
  uid: ['uid', string()],
  v: ['__v', number()],
});
