/**
 * Beepo Core MicroserviceLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Example15 {
  ciphertext: string;
}

export const example15Schema: Schema<Example15> = object({
  ciphertext: ['ciphertext', string()],
});
