/**
 * Beepo Core MicroserviceLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Example13 {
  encrypted: string;
  iv: string;
}

export const example13Schema: Schema<Example13> = object({
  encrypted: ['encrypted', string()],
  iv: ['iv', string()],
});
