/**
 * Beepo Core MicroserviceLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Example14 {
  decrypted: string;
}

export const example14Schema: Schema<Example14> = object({
  decrypted: ['decrypted', string()],
});
