/**
 * Beepo Core MicroserviceLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface HashSHA256Request {
  message: string;
}

export const hashSHA256RequestSchema: Schema<HashSHA256Request> = object({
  message: ['message', string()],
});
