/**
 * Beepo Core MicroserviceLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface RSADecryptionRequest {
  ciphertext: string;
  privateKeyPem: string;
}

export const rSADecryptionRequestSchema: Schema<RSADecryptionRequest> = object({
  ciphertext: ['ciphertext', string()],
  privateKeyPem: ['privateKeyPem', string()],
});
