/**
 * Beepo Core MicroserviceLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface RSAEncryptionRequest {
  message: string;
  publicKeyPem: string;
}

export const rSAEncryptionRequestSchema: Schema<RSAEncryptionRequest> = object({
  message: ['message', string()],
  publicKeyPem: ['publicKeyPem', string()],
});
